datasource:
  db:
    username: ""
    password: ""
    driver: "org.mariadb.jdbc.Driver"
    url: "jdbc:mariadb://172.17.0.1:3306/lolosia?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8"

server:
  port: 58801

spring:
  devtools:
    restart:
      enabled: true
  jackson:
    time-zone: GMT+8
  application:
    name: "lolosia-backend"

logging:
  charset:
    console: GB18030
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%-5p}) %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: INFO
  config: "classpath:logback-spring.xml"